# Server Configuration
server.port=8080

# MongoDB Configuration - MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://hospital_management:HospitalDB_123@cluster0.0euttbf.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=hospital_management
spring.data.mongodb.auto-index-creation=true

# Application Name
spring.application.name=hospital-management

# Logging
logging.level.root=INFO
logging.level.org.springframework.data.mongodb=DEBUG

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**